name: Automated App Deployment

on:
  push:
    branches: [ main, master ]
    paths:
      - 'chatter/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: chatter
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Firebase CLI and EAS CLI
      run: |
        npm install -g firebase-tools
        npm install -g eas-cli
      
    - name: Deploy APK to Firebase App Distribution
      run: |
        cd chatter
        ./deploy-with-eas-apk.sh
      env:
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
    - name: Success Message
      run: |
        echo "🎉 AUTOMATED APP DEPLOYMENT COMPLETED!"
        echo "📱 Android APK deployed to Firebase App Distribution"
        echo "📧 Testers will receive email invitations"
        echo "🆓 Free Firebase App Distribution - No Google Play Store required!"
        echo ""
        echo "🔗 Firebase Console: https://console.firebase.google.com/project/ai-msging/appdistribution" 